substitutions:
  _LOCATION: asia-northeast1
  _REPOSITORY: version-final
  _IMAGE_NAME: version-final
  _TAG: $SHORT_SHA        # ← ここを SHORT_SHA に
  _SERVICE_NAME: version-final
  _REGION: asia-northeast1

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/kaniko-project/executor:v1.23.2-debug'  # ← latestは避けて固定推奨
    args:
      - --destination=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - --dockerfile=./Dockerfile
      - --context=.
      - --cache=true
      - --cache-ttl=8h
      - --compressed-caching=false
      - --cache-copy-layers=true
    id: "Build & Push"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:474.0.0'  # ← これも固定推奨
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - 2Gi
      - --concurrency
      - 10                 # ← 数値で、1は避ける（性能・安定のため）
      # （Cloud Run 側に環境変数/シークレットを設定済みなら何も渡さない）
    id: Deploy
